models/Category.php
<?php


namespace app\models;


use yii\db\ActiveRecord;

class Category extends ActiveRecord
{
    public static function tableName()
    {
        return 'category';
    }

    public function attributeLabels()
    {
        return [
            'name' => 'Категория',
        ];
    }



}

controllers/CategoryController.php
<?php


namespace app\controllers;
use Yii;

use app\models\Category;
use app\models\Products;
use yii\web\Controller;

class CategoryController extends Controller
{
    public function actionAllCategory(){
        $this->view->title = 'Все категории';
        $categories = Category::find()->all();
        $products = Products::find()->with('category')->all();
        $cat  = Category::find()->all();
        return $this->render('all-category', compact('products','categories'));
    }
    public function actionCategory($id)
    {
        $id = Yii::$app->request->get('id');
        $products = Products::find()->where(['id' => $id])->all();
        return $this->render('category', compact('products'));
    }

    public function actionMasks(){
        $this->view->title = "Сварочные маски";
        $products = Products::find()->where(['id_category' => 1])->all();
        return $this->render('masks', compact('products'));
    }
    public function actionGloves(){
        $this->view->title = "Перчатки";
        $products = Products::find()->where(['id_category' => 2])->all();
        return $this->render('masks', compact('products'));
    }

}

views/category/all-category.php
<?php
use yii\widgets\ActiveForm;
use yii\helpers\Html;
use yii\helpers\ArrayHelper;
?>
<div class="site-index">
    <div class="section">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="col-md-12 text-center">
                        <div class="btn-group">
                            <a   class="btn btn-success"" >Все</a>
                            <a href="masks"  class="active btn btn-primary  " >Маски</a>
                            <a href="gloves" class="btn btn-primary" >Перчатки</a>
                            <a href="masks" class="btn btn-primary">Костюмы</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php $this->registerCssFile('web/to/style.css'); ?>
<div class="filter-ref-today">
<!--    <a name="" href=" --><?// yii\helpers\Url::to (['products/viewproduct', 'id'=>$product->id])   ?><!--" >-->

    <div class="container">
        <div class="row">
            <?php foreach ($categories as $cat): ?>
            <div class="col-md-4 col-sm-4 col-xs-12 text-center ">

                    <?= $cat->name ?></br>
<!--                <div class="col-md-10 "">-->
                    <? echo Html::img('@web/'.$cat->image, ['class' =>'img-responsive'])?>
<!--                </div>-->
            <?= $cat->description ?></br>
            </div>
            <?php endforeach; ?>
        </div>
    </div>

<!--            --><?php //foreach ($products as $product): ?>
<!--                <div class="section">-->
<!--                    <div class="col-md-3 task-item">-->
<!--                        <div class="thumbnail">-->
<!--                            <a href=" --><?//= yii\helpers\Url::to (['/category/category', 'id' => $product->id])  ?><!--">-->
<!--                             --><?// echo Html::img('@web/'.$product->image, ['class' =>'img-responsive'])?>
<!--                                <div > --><?//= $product->name ?><!-- </div>-->
<!--                            </a>-->
<!--                        <hr>-->
<!--                        <div> --><?//= $product->price ?><!--</div>-->
<!--                         <hr>-->
<!--                      <div> --><?//= $product->description ?><!--</div>-->
<!--                    </div>-->
<!--                    </div>-->
<!--               </div>-->
<!---->
<!---->
<!--           --><?php //foreach ($products as $product): ?>
</div>


<!--<div class="filter-ref-today">

    <div class="section">
        <div class="col-md-3 task-item">
            <div class="section">
                <div class="col-md-3 task-item">
      <?php
/*               foreach ($products as $product){
           echo Html::img('@web/'.$product->image);
                   echo '<div>' .$product->price. '</div>';
                   echo '<div>' .$product->description. '</div>';
               }

                   */?>


        </div>
    </div>
        </div>
    </div>
</div>-->

views/category/category.php
<?php
use yii\widgets\ActiveForm;
use yii\helpers\Html;
use yii\helpers\ArrayHelper;
?>

<?php $this->registerCssFile('web/to/style.css'); ?>
<div class="filter-ref-today">
    <!--    <a name="" href=" --><?// yii\helpers\Url::to (['products/viewproduct', 'id'=>$product->id])   ?><!--" >-->
    <?php foreach ($products as $product): ?>
        <div class="section">
            <div class="col-md-3 task-item">
                <div class="thumbnail">
                    <a href=" <?= yii\helpers\Url::to (['/category/masks', 'id' => $product->id])  ?>">
                        <? echo Html::img('@web/'.$product->image, ['class' =>'img-responsive'])?>
                        <div > <?= $product->name ?> </div>
                    </a>
                    <hr>
                    <div> <?= $product->price ?></div>
                    <hr>
                    <div> <?= $product->description ?></div>
                </div>
            </div>
        </div>


    <?php endforeach;?>
</div>